<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

/**
 * Privacy provider for the AI Quiz Generator plugin.
 *
 * Implements GDPR compliance.
 *
 * @package    local_hlai_quizgen
 * @copyright  2025 Human Logic Software LLC
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

namespace local_hlai_quizgen\privacy;

use core_privacy\local\metadata\collection;
use core_privacy\local\metadata\provider as metadata_provider;
use core_privacy\local\request\approved_contextlist;
use core_privacy\local\request\approved_userlist;
use core_privacy\local\request\contextlist;
use core_privacy\local\request\core_userlist_provider;
use core_privacy\local\request\plugin\provider as plugin_provider;
use core_privacy\local\request\transform;
use core_privacy\local\request\userlist;
use core_privacy\local\request\writer;


/**
 * Privacy provider class.
 */
class provider implements
    core_userlist_provider,
    metadata_provider,
    plugin_provider {
    /**
     * Get metadata about data stored by this plugin.
     *
     * @param collection $collection Collection to add items to
     * @return collection Updated collection
     */
    public static function get_metadata(collection $collection): collection {
        // Request data.
        $collection->add_database_table(
            'local_hlai_quizgen_requests',
            [
                'userid' => 'privacy:metadata:local_hlai_quizgen_requests:userid',
                'timecreated' => 'privacy:metadata:local_hlai_quizgen_requests:timecreated',
            ],
            'privacy:metadata:local_hlai_quizgen_requests'
        );

        // User settings.
        $collection->add_database_table(
            'local_hlai_quizgen_settings',
            [
                'userid' => 'privacy:metadata:local_hlai_quizgen_settings:userid',
                'setting_value' => 'privacy:metadata:local_hlai_quizgen_settings:setting_value',
            ],
            'privacy:metadata:local_hlai_quizgen_settings'
        );

        // Logs.
        $collection->add_database_table(
            'local_hlai_quizgen_logs',
            [
                'userid' => 'privacy:metadata:local_hlai_quizgen_logs:userid',
                'action' => 'privacy:metadata:local_hlai_quizgen_logs:action',
                'timecreated' => 'privacy:metadata:local_hlai_quizgen_logs:timecreated',
            ],
            'privacy:metadata:local_hlai_quizgen_logs'
        );

        // Questions generated by users.
        $collection->add_database_table(
            'local_hlai_quizgen_questions',
            [
                'userid' => 'privacy:metadata:local_hlai_quizgen_questions:userid',
                'timecreated' => 'privacy:metadata:local_hlai_quizgen_questions:timecreated',
            ],
            'privacy:metadata:local_hlai_quizgen_questions'
        );

        // Wizard session state.
        $collection->add_database_table(
            'local_hlai_quizgen_wizard_state',
            [
                'userid' => 'privacy:metadata:local_hlai_quizgen_wizard_state:userid',
                'timecreated' => 'privacy:metadata:local_hlai_quizgen_wizard_state:timecreated',
            ],
            'privacy:metadata:local_hlai_quizgen_wizard_state'
        );

        // Rate limit tracking.
        $collection->add_database_table(
            'local_hlai_quizgen_ratelimit_log',
            [
                'userid' => 'privacy:metadata:local_hlai_quizgen_ratelimit_log:userid',
                'timecreated' => 'privacy:metadata:local_hlai_quizgen_ratelimit_log:timecreated',
            ],
            'privacy:metadata:local_hlai_quizgen_ratelimit_log'
        );

        // User templates.
        $collection->add_database_table(
            'local_hlai_quizgen_templates',
            [
                'userid' => 'privacy:metadata:local_hlai_quizgen_templates:userid',
                'timecreated' => 'privacy:metadata:local_hlai_quizgen_templates:timecreated',
            ],
            'privacy:metadata:local_hlai_quizgen_templates'
        );

        // Peer review data.
        $collection->add_database_table(
            'local_hlai_quizgen_reviews',
            [
                'reviewerid' => 'privacy:metadata:local_hlai_quizgen_reviews:reviewerid',
                'submitterid' => 'privacy:metadata:local_hlai_quizgen_reviews:submitterid',
                'timecreated' => 'privacy:metadata:local_hlai_quizgen_reviews:timecreated',
            ],
            'privacy:metadata:local_hlai_quizgen_reviews'
        );

        // AI refinements.
        $collection->add_database_table(
            'local_hlai_quizgen_refinements',
            [
                'userid' => 'privacy:metadata:local_hlai_quizgen_refinements:userid',
                'timecreated' => 'privacy:metadata:local_hlai_quizgen_refinements:timecreated',
            ],
            'privacy:metadata:local_hlai_quizgen_refinements'
        );

        // Review comments.
        $collection->add_database_table(
            'local_hlai_quizgen_review_comments',
            [
                'userid' => 'privacy:metadata:local_hlai_quizgen_review_comments:userid',
                'timecreated' => 'privacy:metadata:local_hlai_quizgen_review_comments:timecreated',
            ],
            'privacy:metadata:local_hlai_quizgen_review_comments'
        );

        // Review ratings.
        $collection->add_database_table(
            'local_hlai_quizgen_review_ratings',
            [
                'userid' => 'privacy:metadata:local_hlai_quizgen_review_ratings:userid',
                'timecreated' => 'privacy:metadata:local_hlai_quizgen_review_ratings:timecreated',
            ],
            'privacy:metadata:local_hlai_quizgen_review_ratings'
        );

        // Question revisions.
        $collection->add_database_table(
            'local_hlai_quizgen_revisions',
            [
                'userid' => 'privacy:metadata:local_hlai_quizgen_revisions:userid',
                'timecreated' => 'privacy:metadata:local_hlai_quizgen_revisions:timecreated',
            ],
            'privacy:metadata:local_hlai_quizgen_revisions'
        );

        // Review activity log.
        $collection->add_database_table(
            'local_hlai_quizgen_review_log',
            [
                'userid' => 'privacy:metadata:local_hlai_quizgen_review_log:userid',
                'timecreated' => 'privacy:metadata:local_hlai_quizgen_review_log:timecreated',
            ],
            'privacy:metadata:local_hlai_quizgen_review_log'
        );

        // Refinement suggestions.
        $collection->add_database_table(
            'local_hlai_quizgen_refine_suggest',
            [
                'userid' => 'privacy:metadata:local_hlai_quizgen_refine_suggest:userid',
                'timecreated' => 'privacy:metadata:local_hlai_quizgen_refine_suggest:timecreated',
            ],
            'privacy:metadata:local_hlai_quizgen_refine_suggest'
        );

        // Question edit history.
        $collection->add_database_table(
            'local_hlai_quizgen_qst_history',
            [
                'userid' => 'privacy:metadata:local_hlai_quizgen_qst_history:userid',
                'timecreated' => 'privacy:metadata:local_hlai_quizgen_qst_history:timecreated',
            ],
            'privacy:metadata:local_hlai_quizgen_qst_history'
        );

        // External data sent to AI gateway.
        $collection->add_external_location_link(
            'aigateway',
            [
                'content' => 'privacy:metadata:external:aigateway:content',
            ],
            'privacy:metadata:external:aigateway:purpose'
        );

        return $collection;
    }

    /**
     * Get contexts containing user data.
     *
     * @param int $userid User ID
     * @return contextlist Context list
     */
    public static function get_contexts_for_userid(int $userid): contextlist {
        $contextlist = new contextlist();

        // Get contexts where user has requests.
        $sql = "SELECT DISTINCT ctx.id
                  FROM {context} ctx
                  JOIN {course} c ON c.id = ctx.instanceid AND ctx.contextlevel = :courselevel
                  JOIN {local_hlai_quizgen_requests} r ON r.courseid = c.id
                 WHERE r.userid = :userid";

        $contextlist->add_from_sql($sql, [
            'courselevel' => CONTEXT_COURSE,
            'userid' => $userid,
        ]);

        return $contextlist;
    }

    /**
     * Get users in a context.
     *
     * @param userlist $userlist User list
     * @return void
     */
    public static function get_users_in_context(userlist $userlist): void {
        $context = $userlist->get_context();

        if ($context->contextlevel != CONTEXT_COURSE) {
            return;
        }

        // Get users with requests in this course.
        $sql = "SELECT r.userid
                  FROM {local_hlai_quizgen_requests} r
                 WHERE r.courseid = :courseid";

        $userlist->add_from_sql('userid', $sql, ['courseid' => $context->instanceid]);
    }

    /**
     * Export user data.
     *
     * @param approved_contextlist $contextlist Approved contexts
     * @return void
     */
    public static function export_user_data(approved_contextlist $contextlist): void {
        global $DB;

        $userid = $contextlist->get_user()->id;

        foreach ($contextlist->get_contexts() as $context) {
            if ($context->contextlevel != CONTEXT_COURSE) {
                continue;
            }

            $courseid = $context->instanceid;

            // Export requests.
            $requests = $DB->get_records('local_hlai_quizgen_requests', [
                'courseid' => $courseid,
                'userid' => $userid,
            ]);

            if (!empty($requests)) {
                $data = [];
                foreach ($requests as $request) {
                    $data[] = [
                        'status' => $request->status,
                        'total_questions' => $request->total_questions,
                        'questions_generated' => $request->questions_generated,
                        'processing_mode' => $request->processing_mode,
                        'timecreated' => transform::datetime($request->timecreated),
                        'timecompleted' => $request->timecompleted ? transform::datetime($request->timecompleted) : '-',
                    ];
                }

                writer::with_context($context)->export_data(
                    [get_string('pluginname', 'local_hlai_quizgen'), 'requests'],
                    (object)['requests' => $data]
                );
            }

            // Export settings.
            $settings = $DB->get_records('local_hlai_quizgen_settings', [
                'userid' => $userid,
                'courseid' => $courseid,
            ]);

            if (!empty($settings)) {
                $data = [];
                foreach ($settings as $setting) {
                    $data[$setting->setting_name] = $setting->setting_value;
                }

                writer::with_context($context)->export_data(
                    [get_string('pluginname', 'local_hlai_quizgen'), 'settings'],
                    (object)$data
                );
            }

            // Export questions.
            $questions = $DB->get_records('local_hlai_quizgen_questions', [
                'userid' => $userid,
            ]);

            if (!empty($questions)) {
                $data = [];
                foreach ($questions as $question) {
                    $data[] = [
                        'questiontext' => $question->questiontext,
                        'questiontype' => $question->questiontype,
                        'difficulty' => $question->difficulty,
                        'blooms_level' => $question->blooms_level,
                        'status' => $question->status,
                        'validation_score' => $question->validation_score,
                        'regeneration_count' => $question->regeneration_count,
                        'timecreated' => transform::datetime($question->timecreated),
                    ];
                }

                writer::with_context($context)->export_data(
                    [get_string('pluginname', 'local_hlai_quizgen'), 'questions'],
                    (object)['questions' => $data]
                );
            }

            // Export reviews.
            $reviews = $DB->get_records('local_hlai_quizgen_reviews', [
                'reviewerid' => $userid,
            ]);

            if (!empty($reviews)) {
                $data = [];
                foreach ($reviews as $review) {
                    $data[] = [
                        'status' => $review->status,
                        'decision' => $review->decision,
                        'decision_comments' => $review->decision_comments,
                        'review_type' => $review->review_type,
                        'timecreated' => transform::datetime($review->timecreated),
                    ];
                }

                writer::with_context($context)->export_data(
                    [get_string('pluginname', 'local_hlai_quizgen'), 'reviews'],
                    (object)['reviews' => $data]
                );
            }

            // Export refinements.
            $refinements = $DB->get_records('local_hlai_quizgen_refinements', [
                'userid' => $userid,
            ]);

            if (!empty($refinements)) {
                $data = [];
                foreach ($refinements as $refinement) {
                    $data[] = [
                        'refinement_type' => $refinement->refinement_type,
                        'changes' => $refinement->changes,
                        'improvements_applied' => $refinement->improvements_applied,
                        'timecreated' => transform::datetime($refinement->timecreated),
                    ];
                }

                writer::with_context($context)->export_data(
                    [get_string('pluginname', 'local_hlai_quizgen'), 'refinements'],
                    (object)['refinements' => $data]
                );
            }
        }
    }

    /**
     * Delete user data for approved contexts.
     *
     * @param \context $context The context to delete data for
     * @return void
     */
    public static function delete_data_for_all_users_in_context(\context $context): void {
        global $DB;

        if ($context->contextlevel != CONTEXT_COURSE) {
            return;
        }

        $courseid = $context->instanceid;

        // Get all user IDs associated with requests in this course.
        $userids = $DB->get_fieldset_select(
            'local_hlai_quizgen_requests',
            'DISTINCT userid',
            'courseid = :courseid',
            ['courseid' => $courseid]
        );

        // Get all requests for this course.
        $requests = $DB->get_records('local_hlai_quizgen_requests', ['courseid' => $courseid]);

        foreach ($requests as $request) {
            self::delete_request_data($request->id);
        }

        // Delete data from additional tables for all users in this context.
        foreach ($userids as $userid) {
            // Delete reviews where user is the reviewer or the submitter.
            $DB->delete_records('local_hlai_quizgen_reviews', [
                'reviewerid' => $userid,
            ]);
            $DB->delete_records('local_hlai_quizgen_reviews', [
                'submitterid' => $userid,
            ]);

            // Delete refinements.
            $DB->delete_records('local_hlai_quizgen_refinements', [
                'userid' => $userid,
            ]);

            // Delete review comments.
            $DB->delete_records('local_hlai_quizgen_review_comments', [
                'userid' => $userid,
            ]);

            // Delete review ratings.
            $DB->delete_records('local_hlai_quizgen_review_ratings', [
                'userid' => $userid,
            ]);

            // Delete revisions.
            $DB->delete_records('local_hlai_quizgen_revisions', [
                'userid' => $userid,
            ]);

            // Delete review log.
            $DB->delete_records('local_hlai_quizgen_review_log', [
                'userid' => $userid,
            ]);

            // Delete refinement suggestions.
            $DB->delete_records('local_hlai_quizgen_refine_suggest', [
                'userid' => $userid,
            ]);

            // Delete question history.
            $DB->delete_records('local_hlai_quizgen_qst_history', [
                'userid' => $userid,
            ]);

            // Delete wizard state.
            $DB->delete_records('local_hlai_quizgen_wizard_state', [
                'userid' => $userid,
            ]);

            // Delete rate limit log.
            $DB->delete_records('local_hlai_quizgen_ratelimit_log', [
                'userid' => $userid,
            ]);

            // Delete templates.
            $DB->delete_records('local_hlai_quizgen_templates', [
                'userid' => $userid,
            ]);

            // Delete user settings.
            $DB->delete_records('local_hlai_quizgen_settings', [
                'userid' => $userid,
                'courseid' => $courseid,
            ]);

            // Delete user logs.
            $DB->delete_records('local_hlai_quizgen_logs', [
                'userid' => $userid,
            ]);
        }
    }

    /**
     * Delete user data.
     *
     * @param approved_contextlist $contextlist Approved contexts
     * @return void
     */
    public static function delete_data_for_user(approved_contextlist $contextlist): void {
        global $DB;

        $userid = $contextlist->get_user()->id;

        foreach ($contextlist->get_contexts() as $context) {
            if ($context->contextlevel != CONTEXT_COURSE) {
                continue;
            }

            $courseid = $context->instanceid;

            // Delete user's requests.
            $requests = $DB->get_records('local_hlai_quizgen_requests', [
                'courseid' => $courseid,
                'userid' => $userid,
            ]);

            foreach ($requests as $request) {
                self::delete_request_data($request->id);
            }

            // Delete user settings.
            $DB->delete_records('local_hlai_quizgen_settings', [
                'userid' => $userid,
                'courseid' => $courseid,
            ]);

            // Delete user logs.
            $DB->delete_records('local_hlai_quizgen_logs', [
                'userid' => $userid,
            ]);

            // Delete reviews where user is the reviewer or the submitter.
            $DB->delete_records('local_hlai_quizgen_reviews', [
                'reviewerid' => $userid,
            ]);
            $DB->delete_records('local_hlai_quizgen_reviews', [
                'submitterid' => $userid,
            ]);

            // Delete refinements.
            $DB->delete_records('local_hlai_quizgen_refinements', [
                'userid' => $userid,
            ]);

            // Delete review comments.
            $DB->delete_records('local_hlai_quizgen_review_comments', [
                'userid' => $userid,
            ]);

            // Delete review ratings.
            $DB->delete_records('local_hlai_quizgen_review_ratings', [
                'userid' => $userid,
            ]);

            // Delete revisions.
            $DB->delete_records('local_hlai_quizgen_revisions', [
                'userid' => $userid,
            ]);

            // Delete review log.
            $DB->delete_records('local_hlai_quizgen_review_log', [
                'userid' => $userid,
            ]);

            // Delete refinement suggestions.
            $DB->delete_records('local_hlai_quizgen_refine_suggest', [
                'userid' => $userid,
            ]);

            // Delete question history.
            $DB->delete_records('local_hlai_quizgen_qst_history', [
                'userid' => $userid,
            ]);

            // Delete wizard state.
            $DB->delete_records('local_hlai_quizgen_wizard_state', [
                'userid' => $userid,
            ]);

            // Delete rate limit log.
            $DB->delete_records('local_hlai_quizgen_ratelimit_log', [
                'userid' => $userid,
            ]);

            // Delete templates.
            $DB->delete_records('local_hlai_quizgen_templates', [
                'userid' => $userid,
            ]);
        }
    }

    /**
     * Delete data for users in approved userlist.
     *
     * @param approved_userlist $userlist Approved users
     * @return void
     */
    public static function delete_data_for_users(approved_userlist $userlist): void {
        global $DB;

        $context = $userlist->get_context();

        if ($context->contextlevel != CONTEXT_COURSE) {
            return;
        }

        $courseid = $context->instanceid;
        $userids = $userlist->get_userids();

        foreach ($userids as $userid) {
            // Delete user's requests.
            $requests = $DB->get_records('local_hlai_quizgen_requests', [
                'courseid' => $courseid,
                'userid' => $userid,
            ]);

            foreach ($requests as $request) {
                self::delete_request_data($request->id);
            }

            // Delete user settings.
            $DB->delete_records('local_hlai_quizgen_settings', [
                'userid' => $userid,
                'courseid' => $courseid,
            ]);

            // Delete user logs.
            $DB->delete_records('local_hlai_quizgen_logs', ['userid' => $userid]);

            // Delete reviews where user is the reviewer or the submitter.
            $DB->delete_records('local_hlai_quizgen_reviews', [
                'reviewerid' => $userid,
            ]);
            $DB->delete_records('local_hlai_quizgen_reviews', [
                'submitterid' => $userid,
            ]);

            // Delete refinements.
            $DB->delete_records('local_hlai_quizgen_refinements', [
                'userid' => $userid,
            ]);

            // Delete review comments.
            $DB->delete_records('local_hlai_quizgen_review_comments', [
                'userid' => $userid,
            ]);

            // Delete review ratings.
            $DB->delete_records('local_hlai_quizgen_review_ratings', [
                'userid' => $userid,
            ]);

            // Delete revisions.
            $DB->delete_records('local_hlai_quizgen_revisions', [
                'userid' => $userid,
            ]);

            // Delete review log.
            $DB->delete_records('local_hlai_quizgen_review_log', [
                'userid' => $userid,
            ]);

            // Delete refinement suggestions.
            $DB->delete_records('local_hlai_quizgen_refine_suggest', [
                'userid' => $userid,
            ]);

            // Delete question history.
            $DB->delete_records('local_hlai_quizgen_qst_history', [
                'userid' => $userid,
            ]);

            // Delete wizard state.
            $DB->delete_records('local_hlai_quizgen_wizard_state', [
                'userid' => $userid,
            ]);

            // Delete rate limit log.
            $DB->delete_records('local_hlai_quizgen_ratelimit_log', [
                'userid' => $userid,
            ]);

            // Delete templates.
            $DB->delete_records('local_hlai_quizgen_templates', [
                'userid' => $userid,
            ]);
        }
    }

    /**
     * Delete all data for a request.
     *
     * @param int $requestid Request ID
     * @return void
     */
    private static function delete_request_data(int $requestid): void {
        global $DB;

        // Get questions.
        $questions = $DB->get_records('local_hlai_quizgen_questions', ['requestid' => $requestid]);

        foreach ($questions as $question) {
            $DB->delete_records('local_hlai_quizgen_answers', ['questionid' => $question->id]);
        }

        $DB->delete_records('local_hlai_quizgen_questions', ['requestid' => $requestid]);
        $DB->delete_records('local_hlai_quizgen_topics', ['requestid' => $requestid]);
        $DB->delete_records('local_hlai_quizgen_logs', ['requestid' => $requestid]);
        $DB->delete_records('local_hlai_quizgen_requests', ['id' => $requestid]);
    }
}
